# Generated by Django 2.0 on 2017-12-25 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0005_remove_list_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='list',
            new_name='list_field',
        ),
    ]
