# Generated by Django 2.0 on 2017-12-25 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0006_auto_20171225_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='list_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lists.List'),
        ),
    ]
