# Generated by Django 2.0 on 2018-01-01 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0007_auto_20171225_1550'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='list_field',
            new_name='list',
        ),
    ]
