# Generated by Django 2.0 on 2018-03-10 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0009_auto_20180216_1508'),
        ('lists', '0010_auto_20180208_0951'),
    ]

    operations = [
    ]
