# Generated by Django 2.0 on 2018-03-22 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0012_auto_20180322_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='text',
            field=models.TextField(),
        ),
    ]
