# Generated by Django 2.0 on 2018-03-23 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0011_merge_20180310_1433'),
        ('lists', '0013_auto_20180322_1737'),
    ]

    operations = [
    ]
